// Coups de cœur de Filmable : des films choisis à la main, chacun avec une phrase pour donner envie.
// Les mêmes pour tout le monde ; « Aujourd'hui » en tire un que tu n'as pas vu.
// Chaque film est retrouvé sur TMDB par son titre (original ou connu) et son année.

export type Pick = [title: string, year: number, hook: string];

export const PICKS: Pick[] = [
  ["Cléo de 5 à 7", 1962, "Un après-midi de juin à Paris, presque en temps réel : une chanteuse attend un résultat d'analyse et regarde enfin la ville."],
  ["Le Samouraï", 1967, "Un tueur, une chambre nue, un oiseau en cage. Melville réduit le polar à ses gestes."],
  ["Chungking Express", 1994, "Deux policiers, deux chagrins d'amour, un snack-bar de Hong Kong. Wong Kar-wai à toute vitesse."],
  ["Stalker", 1979, "Trois hommes traversent la Zone vers une chambre qui exaucerait les désirs. Tarkovski prend son temps, et c'est tout l'enjeu."],
  ["Tokyo Story", 1953, "Un couple âgé rend visite à ses enfants trop occupés. Ozu filme à hauteur de tatami ce que tout le monde finit par vivre."],
  ["In the Mood for Love", 2000, "Deux voisins découvrent que leurs conjoints les trompent ensemble. Des couloirs étroits, des robes, une valse qui revient."],
  ["Mulholland Drive", 2001, "Une actrice débarque à Hollywood, une femme a perdu la mémoire. Le rêve de David Lynch se referme sur lui-même."],
  ["Memories of Murder", 2003, "Des meurtres en série dans la campagne coréenne de 1986, et deux policiers dépassés. Bong Joon-ho avant Parasite."],
  ["Le Salaire de la peur", 1953, "Quatre hommes, deux camions, de la nitroglycérine sur des pistes défoncées. Le suspense à l'état brut."],
  ["La Jetée", 1962, "Vingt-huit minutes faites presque uniquement de photographies fixes : Chris Marker invente un voyage dans le temps."],
  ["Paris, Texas", 1984, "Un homme sort du désert après quatre ans d'absence. Wenders, la guitare de Ry Cooder, et un monologue derrière une vitre sans tain."],
  ["Rashomon", 1950, "Un crime, quatre récits qui se contredisent. Kurosawa apprend à douter de ce qu'on voit."],
  ["Vertigo", 1958, "Un détective sujet au vertige suit une femme dans San Francisco. L'obsession selon Hitchcock."],
  ["Playtime", 1967, "Monsieur Hulot perdu dans un Paris de verre et d'acier construit pour le film. À voir sur le plus grand écran possible."],
  ["Once Upon a Time in the West", 1968, "Trois tueurs, une gare dans le désert, un harmonica. Leone étire le temps jusqu'à l'opéra."],
  ["The Thing", 1982, "Une base en Antarctique, douze hommes, et quelque chose qui peut prendre l'apparence de n'importe lequel d'entre eux."],
  ["Heat", 1995, "Un braqueur méthodique, un flic obsessionnel, Los Angeles la nuit. Et une fusillade en plein centre-ville."],
  ["Barry Lyndon", 1975, "L'ascension et la chute d'un aventurier irlandais, filmées à la lumière des bougies."],
  ["Ikiru", 1952, "Un fonctionnaire apprend qu'il va mourir et cherche, enfin, à faire une chose utile."],
  ["Sunset Boulevard", 1950, "Un scénariste fauché se réfugie chez une star oubliée du muet. Hollywood raconté par un mort."],
  ["The Third Man", 1949, "Vienne en ruines, un ami qu'on croyait mort, une grande roue et une cithare."],
  ["8½", 1963, "Un cinéaste en panne d'inspiration, cerné par ses souvenirs et ses femmes. Fellini se met en scène."],
  ["Persona", 1966, "Une actrice qui ne parle plus, une infirmière qui parle trop, une maison au bord de la mer. Bergman au plus radical."],
  ["Come and See", 1985, "La guerre vue par un adolescent biélorusse. L'un des films les plus éprouvants jamais tournés."],
  ["Close-Up", 1990, "Un homme se fait passer pour le cinéaste Makhmalbaf. Kiarostami rejoue l'affaire avec les vrais protagonistes."],
  ["Yi Yi", 2000, "Une famille de Taipei, d'un mariage à un enterrement. Edward Yang filme tous les âges de la vie à la fois."],
  ["Beau travail", 1999, "La Légion étrangère à Djibouti, des corps à l'entraînement, une jalousie sourde. Claire Denis."],
  ["Portrait de la jeune fille en feu", 2019, "Une peintre doit faire le portrait d'une femme qui refuse de poser. Tout passe par le regard."],
  ["Sans soleil", 1983, "Des lettres lues par une voix de femme, des images du Japon, de Guinée-Bissau, d'Islande. Un film-essai qui ne ressemble à aucun autre."],
  ["Oldboy", 2003, "Enfermé quinze ans sans savoir pourquoi, un homme est relâché avec cinq jours pour comprendre."],
  ["Burning", 2018, "Un jeune écrivain, une amie d'enfance, un homme riche qui brûle des serres. Le mystère ne se résout pas."],
  ["A Brighter Summer Day", 1991, "Taipei au début des années 1960, des bandes d'adolescents et un meurtre. Quatre heures qui passent comme un roman."],
  ["Les Yeux sans visage", 1960, "Un chirurgien tente de rendre un visage à sa fille défigurée. La poésie et l'horreur chez Franju."],
  ["La Haine", 1995, "Vingt-quatre heures avec trois amis de banlieue au lendemain d'une émeute. Noir et blanc, et l'heure qui tourne."],
  ["Un prophète", 2009, "Un jeune détenu apprend la prison, puis le pouvoir. Audiard et Tahar Rahim."],
  ["Perfect Blue", 1997, "Une chanteuse devient actrice et commence à perdre pied. Satoshi Kon, avant tout le monde."],
  ["Grave of the Fireflies", 1988, "Un frère et sa petite sœur dans le Japon de 1945. Un film d'animation qui ne ménage personne."],
  ["The Night of the Hunter", 1955, "Un faux pasteur poursuit deux enfants le long d'une rivière. L'unique film de Charles Laughton, un conte noir."],
  ["The Apartment", 1960, "Un employé prête son appartement aux amours de ses chefs. Billy Wilder, entre comédie et mélancolie."],
  ["Chinatown", 1974, "Un détective privé, une affaire d'eau dans le Los Angeles des années 1930. Tout est plus sale qu'il n'y paraît."],
  ["Do the Right Thing", 1989, "La journée la plus chaude de l'été dans une rue de Brooklyn. Spike Lee fait monter la température."],
  ["Fargo", 1996, "Une rançon qui tourne mal dans la neige du Minnesota, et une policière enceinte qui ne lâche rien."],
  ["Children of Men", 2006, "Plus aucun enfant n'est né depuis dix-huit ans. Des plans-séquences sidérants dans une Angleterre en guerre."],
  ["Aftersun", 2022, "Des vacances en Turquie, un père, sa fille de onze ans, un caméscope. Ce qu'on comprend des années plus tard."],
  ["Past Lives", 2023, "Deux amis d'enfance se retrouvent à New York vingt-quatre ans après. Tout ce qui aurait pu être."],
  ["Drive My Car", 2021, "Un metteur en scène endeuillé, une conductrice taciturne, une Saab rouge. Trois heures qu'on ne voit pas passer."],
  ["Petite Maman", 2021, "Une fillette de huit ans rencontre dans les bois une enfant qui lui ressemble. Céline Sciamma, en soixante-douze minutes."],
  ["Ran", 1985, "Le Roi Lear chez les seigneurs de guerre japonais. Kurosawa à soixante-quinze ans, en couleurs."],
  ["Les Parapluies de Cherbourg", 1964, "Tout est chanté, même les répliques les plus banales. Demy, Legrand, Deneuve, et la guerre d'Algérie qui sépare."],
  ["L'Atalante", 1934, "Une péniche, un jeune couple, un vieux marinier plein de trésors. Le seul long métrage de Jean Vigo."],
  ["The Handmaiden", 2016, "Une servante, une héritière, un escroc, dans la Corée sous occupation japonaise. Rien n'est ce qu'il paraît."],
  ["Stop Making Sense", 1984, "Les Talking Heads sur scène, un costume beaucoup trop grand, une chanson après l'autre. Le film de concert par excellence."],
  ["Paprika", 2006, "Une machine permet d'entrer dans les rêves des autres, et elle est volée. Le dernier long métrage de Satoshi Kon."],
  ["Tampopo", 1985, "Une veuve veut servir les meilleures nouilles de Tokyo, et un routier l'y aide. Un western ramen."],
  ["Victoria", 2015, "Berlin, une nuit, un braquage, et un seul plan de plus de deux heures."],
  ["Wild Strawberries", 1957, "Un vieux professeur fait la route vers la cérémonie qui doit l'honorer, et revisite sa vie en chemin."],
];
